# Generated by Django 5.2.7 on 2025-11-10 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteConstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constructor_id', models.CharField(db_index=True, max_length=64)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_constructors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'constructor_id')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(db_index=True, max_length=64)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_drivers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'driver_id')},
            },
        ),
    ]
