# Generated by Django 5.2.7 on 2025-11-10 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteconstructor',
            name='constructor_id',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='favoriteconstructor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favoritedriver',
            name='driver_id',
            field=models.SlugField(),
        ),
    ]
