"""
Django settings for f1capstone project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i@czi8rg^k0oo%8r7xv#gx8(2ug!#t%g8!n6zhuq6-60u!g!uq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'f1',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'f1capstone.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'f1.context_processors.schedule_menu',
                'f1.context_processors.results_menu',
                'f1.context_processors.drivers_menu',
                'f1.context_processors.api_health',
                'f1.context_processors.constructors_menu',
            ],
        },
    },
]

WSGI_APPLICATION = 'f1capstone.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'


# ---- API CONFIG: single source of truth ----
JOLPICA_BASE = 'https://api.jolpi.ca'
JOLPICA_PREFIX = '/ergast/f1'

# can store paths relative to BASE+PREFIX or absolute URLs. Mixed is fine.
JOLPICA_ENDPOINTS = {
    'season': f'{JOLPICA_PREFIX}/seasons',
    'circuit': f'{JOLPICA_PREFIX}/circuits',

    # 2025-scoped resources (can be parametrized later)
    'race': f'{JOLPICA_PREFIX}/2025/races',
    'constructor': f'{JOLPICA_PREFIX}/2025/constructors',
    'driver': f'{JOLPICA_PREFIX}/2025/drivers',
    'result': f'{JOLPICA_PREFIX}/2025/results',
    'sprint': f'{JOLPICA_PREFIX}/2025/sprint',
    'qualifying': f'{JOLPICA_PREFIX}/2025/qualifying',

    # Round-scoped examples (can format with Python later)
    'pitstop': f'{JOLPICA_PREFIX}/2025/1/pitstops',
    'lap': f'{JOLPICA_PREFIX}/2025/1/laps',

    'driverstanding': f'{JOLPICA_PREFIX}/2025/driverstandings',
    'constructorstanding': f'{JOLPICA_PREFIX}/2025/constructorstandings',
    'status': f'{JOLPICA_PREFIX}/status',
}

# Timeout & retry-like settings (used by my API client)
JOLPICA_HTTP_TIMEOUT = 12


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOGIN_REDIRECT_URL = "f1:my_hub"
LOGOUT_REDIRECT_URL = "f1:index"
LOGIN_URL = "login"  


NEWS_RSS_LIMIT = 8       
NEWS_RSS_TIMEOUT = 5.0
NEWS_RSS_TTL = 30 * 60   

